/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../index';
import * as import2 from '@angular/common';
import * as import3 from '@angular/platform-browser';
import * as import4 from '@angular/http';
import * as import5 from '@angular/forms';
import * as import6 from '../services/error.service';
import * as import7 from '../services/swagger.service';
import * as import8 from '../services/api-key.provider';
import * as import9 from '../services/auth.service';
import * as import10 from '../services/request.builder';
import * as import11 from '../services/http.service';
import * as import12 from './components/api-method-form-control/input-control.component.ngfactory';
import * as import13 from './components/api-method-form-control/select-control.component.ngfactory';
import * as import14 from './components/api-method-form-control/textarea-control.component.ngfactory';
class SwangularModuleInjector extends import0.ɵNgModuleInjector<import1.SwangularModule> {
  _CommonModule_0:import2.CommonModule;
  _ErrorHandler_1:any;
  _APP_INITIALIZER_2:any[];
  _ApplicationInitStatus_3:import0.ApplicationInitStatus;
  _ɵf_4:import0.ɵf;
  _ApplicationRef_5:any;
  _ApplicationModule_6:import0.ApplicationModule;
  _BrowserModule_7:import3.BrowserModule;
  _HttpModule_8:import4.HttpModule;
  _ɵba_9:import5.ɵba;
  _FormsModule_10:import5.FormsModule;
  _ReactiveFormsModule_11:import5.ReactiveFormsModule;
  _SwangularModule_12:import1.SwangularModule;
  __LOCALE_ID_13:any;
  __NgLocalization_14:import2.NgLocaleLocalization;
  __Compiler_15:import0.Compiler;
  __APP_ID_16:any;
  __IterableDiffers_17:any;
  __KeyValueDiffers_18:any;
  __DomSanitizer_19:import3.ɵe;
  __Sanitizer_20:any;
  __HAMMER_GESTURE_CONFIG_21:import3.HammerGestureConfig;
  __EVENT_MANAGER_PLUGINS_22:any[];
  __EventManager_23:import3.EventManager;
  __ɵDomSharedStylesHost_24:import3.ɵDomSharedStylesHost;
  __ɵDomRendererFactory2_25:import3.ɵDomRendererFactory2;
  __RendererFactory2_26:any;
  __ɵSharedStylesHost_27:any;
  __Testability_28:import0.Testability;
  __Meta_29:import3.Meta;
  __Title_30:import3.Title;
  __BrowserXhr_31:import4.BrowserXhr;
  __ResponseOptions_32:import4.BaseResponseOptions;
  __XSRFStrategy_33:any;
  __XHRBackend_34:import4.XHRBackend;
  __RequestOptions_35:import4.BaseRequestOptions;
  __Http_36:any;
  __ɵi_37:import5.ɵi;
  __FormBuilder_38:import5.FormBuilder;
  __ErrorService_39:import6.ErrorService;
  __SwaggerService_40:import7.SwaggerService;
  __ApiKeyProvider_41:import8.ApiKeyProvider;
  __AuthService_42:import9.AuthService;
  __RequestBuilder_43:import10.RequestBuilder;
  __HttpService_44:import11.HttpService;
  constructor(parent:import0.Injector) {
    super(parent,[
      import12.InputControlComponentNgFactory,
      import13.SelectControlComponentNgFactory,
      import14.TextAreaControlComponentNgFactory
    ]
    ,([] as any[]));
  }
  get _LOCALE_ID_13():any {
    if ((this.__LOCALE_ID_13 == null)) { (this.__LOCALE_ID_13 = import0.ɵn(this.parent.get(import0.LOCALE_ID,(null as any)))); }
    return this.__LOCALE_ID_13;
  }
  get _NgLocalization_14():import2.NgLocaleLocalization {
    if ((this.__NgLocalization_14 == null)) { (this.__NgLocalization_14 = new import2.NgLocaleLocalization(this._LOCALE_ID_13)); }
    return this.__NgLocalization_14;
  }
  get _Compiler_15():import0.Compiler {
    if ((this.__Compiler_15 == null)) { (this.__Compiler_15 = new import0.Compiler()); }
    return this.__Compiler_15;
  }
  get _APP_ID_16():any {
    if ((this.__APP_ID_16 == null)) { (this.__APP_ID_16 = import0.ɵg()); }
    return this.__APP_ID_16;
  }
  get _IterableDiffers_17():any {
    if ((this.__IterableDiffers_17 == null)) { (this.__IterableDiffers_17 = import0.ɵl()); }
    return this.__IterableDiffers_17;
  }
  get _KeyValueDiffers_18():any {
    if ((this.__KeyValueDiffers_18 == null)) { (this.__KeyValueDiffers_18 = import0.ɵm()); }
    return this.__KeyValueDiffers_18;
  }
  get _DomSanitizer_19():import3.ɵe {
    if ((this.__DomSanitizer_19 == null)) { (this.__DomSanitizer_19 = new import3.ɵe(this.parent.get(import3.DOCUMENT))); }
    return this.__DomSanitizer_19;
  }
  get _Sanitizer_20():any {
    if ((this.__Sanitizer_20 == null)) { (this.__Sanitizer_20 = this._DomSanitizer_19); }
    return this.__Sanitizer_20;
  }
  get _HAMMER_GESTURE_CONFIG_21():import3.HammerGestureConfig {
    if ((this.__HAMMER_GESTURE_CONFIG_21 == null)) { (this.__HAMMER_GESTURE_CONFIG_21 = new import3.HammerGestureConfig()); }
    return this.__HAMMER_GESTURE_CONFIG_21;
  }
  get _EVENT_MANAGER_PLUGINS_22():any[] {
    if ((this.__EVENT_MANAGER_PLUGINS_22 == null)) { (this.__EVENT_MANAGER_PLUGINS_22 = [
      new import3.ɵDomEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵKeyEventsPlugin(this.parent.get(import3.DOCUMENT)),
      new import3.ɵHammerGesturesPlugin(this.parent.get(import3.DOCUMENT),this._HAMMER_GESTURE_CONFIG_21)
    ]
    ); }
    return this.__EVENT_MANAGER_PLUGINS_22;
  }
  get _EventManager_23():import3.EventManager {
    if ((this.__EventManager_23 == null)) { (this.__EventManager_23 = new import3.EventManager(this._EVENT_MANAGER_PLUGINS_22,this.parent.get(import0.NgZone))); }
    return this.__EventManager_23;
  }
  get _ɵDomSharedStylesHost_24():import3.ɵDomSharedStylesHost {
    if ((this.__ɵDomSharedStylesHost_24 == null)) { (this.__ɵDomSharedStylesHost_24 = new import3.ɵDomSharedStylesHost(this.parent.get(import3.DOCUMENT))); }
    return this.__ɵDomSharedStylesHost_24;
  }
  get _ɵDomRendererFactory2_25():import3.ɵDomRendererFactory2 {
    if ((this.__ɵDomRendererFactory2_25 == null)) { (this.__ɵDomRendererFactory2_25 = new import3.ɵDomRendererFactory2(this._EventManager_23,this._ɵDomSharedStylesHost_24)); }
    return this.__ɵDomRendererFactory2_25;
  }
  get _RendererFactory2_26():any {
    if ((this.__RendererFactory2_26 == null)) { (this.__RendererFactory2_26 = this._ɵDomRendererFactory2_25); }
    return this.__RendererFactory2_26;
  }
  get _ɵSharedStylesHost_27():any {
    if ((this.__ɵSharedStylesHost_27 == null)) { (this.__ɵSharedStylesHost_27 = this._ɵDomSharedStylesHost_24); }
    return this.__ɵSharedStylesHost_27;
  }
  get _Testability_28():import0.Testability {
    if ((this.__Testability_28 == null)) { (this.__Testability_28 = new import0.Testability(this.parent.get(import0.NgZone))); }
    return this.__Testability_28;
  }
  get _Meta_29():import3.Meta {
    if ((this.__Meta_29 == null)) { (this.__Meta_29 = new import3.Meta(this.parent.get(import3.DOCUMENT))); }
    return this.__Meta_29;
  }
  get _Title_30():import3.Title {
    if ((this.__Title_30 == null)) { (this.__Title_30 = new import3.Title(this.parent.get(import3.DOCUMENT))); }
    return this.__Title_30;
  }
  get _BrowserXhr_31():import4.BrowserXhr {
    if ((this.__BrowserXhr_31 == null)) { (this.__BrowserXhr_31 = new import4.BrowserXhr()); }
    return this.__BrowserXhr_31;
  }
  get _ResponseOptions_32():import4.BaseResponseOptions {
    if ((this.__ResponseOptions_32 == null)) { (this.__ResponseOptions_32 = new import4.BaseResponseOptions()); }
    return this.__ResponseOptions_32;
  }
  get _XSRFStrategy_33():any {
    if ((this.__XSRFStrategy_33 == null)) { (this.__XSRFStrategy_33 = import4.ɵb()); }
    return this.__XSRFStrategy_33;
  }
  get _XHRBackend_34():import4.XHRBackend {
    if ((this.__XHRBackend_34 == null)) { (this.__XHRBackend_34 = new import4.XHRBackend(this._BrowserXhr_31,this._ResponseOptions_32,this._XSRFStrategy_33)); }
    return this.__XHRBackend_34;
  }
  get _RequestOptions_35():import4.BaseRequestOptions {
    if ((this.__RequestOptions_35 == null)) { (this.__RequestOptions_35 = new import4.BaseRequestOptions()); }
    return this.__RequestOptions_35;
  }
  get _Http_36():any {
    if ((this.__Http_36 == null)) { (this.__Http_36 = import4.ɵc(this._XHRBackend_34,this._RequestOptions_35)); }
    return this.__Http_36;
  }
  get _ɵi_37():import5.ɵi {
    if ((this.__ɵi_37 == null)) { (this.__ɵi_37 = new import5.ɵi()); }
    return this.__ɵi_37;
  }
  get _FormBuilder_38():import5.FormBuilder {
    if ((this.__FormBuilder_38 == null)) { (this.__FormBuilder_38 = new import5.FormBuilder()); }
    return this.__FormBuilder_38;
  }
  get _ErrorService_39():import6.ErrorService {
    if ((this.__ErrorService_39 == null)) { (this.__ErrorService_39 = new import6.ErrorService()); }
    return this.__ErrorService_39;
  }
  get _SwaggerService_40():import7.SwaggerService {
    if ((this.__SwaggerService_40 == null)) { (this.__SwaggerService_40 = new import7.SwaggerService(this._Http_36,this._ErrorService_39)); }
    return this.__SwaggerService_40;
  }
  get _ApiKeyProvider_41():import8.ApiKeyProvider {
    if ((this.__ApiKeyProvider_41 == null)) { (this.__ApiKeyProvider_41 = new import8.ApiKeyProvider()); }
    return this.__ApiKeyProvider_41;
  }
  get _AuthService_42():import9.AuthService {
    if ((this.__AuthService_42 == null)) { (this.__AuthService_42 = new import9.AuthService(this._ApiKeyProvider_41,this._ErrorService_39)); }
    return this.__AuthService_42;
  }
  get _RequestBuilder_43():import10.RequestBuilder {
    if ((this.__RequestBuilder_43 == null)) { (this.__RequestBuilder_43 = new import10.RequestBuilder(this._SwaggerService_40,this._ApiKeyProvider_41,this._AuthService_42)); }
    return this.__RequestBuilder_43;
  }
  get _HttpService_44():import11.HttpService {
    if ((this.__HttpService_44 == null)) { (this.__HttpService_44 = new import11.HttpService(this._Http_36,this._ErrorService_39)); }
    return this.__HttpService_44;
  }
  createInternal():import1.SwangularModule {
    this._CommonModule_0 = new import2.CommonModule();
    this._ErrorHandler_1 = import3.ɵa();
    this._APP_INITIALIZER_2 = [
      import0.ɵo,
      import3.ɵc(this.parent.get(import3.NgProbeToken,(null as any)),this.parent.get(import0.NgProbeToken,(null as any)))
    ]
    ;
    this._ApplicationInitStatus_3 = new import0.ApplicationInitStatus(this._APP_INITIALIZER_2);
    this._ɵf_4 = new import0.ɵf(this.parent.get(import0.NgZone),this.parent.get(import0.ɵConsole),this,this._ErrorHandler_1,this.componentFactoryResolver,this._ApplicationInitStatus_3);
    this._ApplicationRef_5 = this._ɵf_4;
    this._ApplicationModule_6 = new import0.ApplicationModule(this._ApplicationRef_5);
    this._BrowserModule_7 = new import3.BrowserModule(this.parent.get(import3.BrowserModule,(null as any)));
    this._HttpModule_8 = new import4.HttpModule();
    this._ɵba_9 = new import5.ɵba();
    this._FormsModule_10 = new import5.FormsModule();
    this._ReactiveFormsModule_11 = new import5.ReactiveFormsModule();
    this._SwangularModule_12 = new import1.SwangularModule();
    return this._SwangularModule_12;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import2.CommonModule)) { return this._CommonModule_0; }
    if ((token === import0.ErrorHandler)) { return this._ErrorHandler_1; }
    if ((token === import0.APP_INITIALIZER)) { return this._APP_INITIALIZER_2; }
    if ((token === import0.ApplicationInitStatus)) { return this._ApplicationInitStatus_3; }
    if ((token === import0.ɵf)) { return this._ɵf_4; }
    if ((token === import0.ApplicationRef)) { return this._ApplicationRef_5; }
    if ((token === import0.ApplicationModule)) { return this._ApplicationModule_6; }
    if ((token === import3.BrowserModule)) { return this._BrowserModule_7; }
    if ((token === import4.HttpModule)) { return this._HttpModule_8; }
    if ((token === import5.ɵba)) { return this._ɵba_9; }
    if ((token === import5.FormsModule)) { return this._FormsModule_10; }
    if ((token === import5.ReactiveFormsModule)) { return this._ReactiveFormsModule_11; }
    if ((token === import1.SwangularModule)) { return this._SwangularModule_12; }
    if ((token === import0.LOCALE_ID)) { return this._LOCALE_ID_13; }
    if ((token === import2.NgLocalization)) { return this._NgLocalization_14; }
    if ((token === import0.Compiler)) { return this._Compiler_15; }
    if ((token === import0.APP_ID)) { return this._APP_ID_16; }
    if ((token === import0.IterableDiffers)) { return this._IterableDiffers_17; }
    if ((token === import0.KeyValueDiffers)) { return this._KeyValueDiffers_18; }
    if ((token === import3.DomSanitizer)) { return this._DomSanitizer_19; }
    if ((token === import0.Sanitizer)) { return this._Sanitizer_20; }
    if ((token === import3.HAMMER_GESTURE_CONFIG)) { return this._HAMMER_GESTURE_CONFIG_21; }
    if ((token === import3.EVENT_MANAGER_PLUGINS)) { return this._EVENT_MANAGER_PLUGINS_22; }
    if ((token === import3.EventManager)) { return this._EventManager_23; }
    if ((token === import3.ɵDomSharedStylesHost)) { return this._ɵDomSharedStylesHost_24; }
    if ((token === import3.ɵDomRendererFactory2)) { return this._ɵDomRendererFactory2_25; }
    if ((token === import0.RendererFactory2)) { return this._RendererFactory2_26; }
    if ((token === import3.ɵSharedStylesHost)) { return this._ɵSharedStylesHost_27; }
    if ((token === import0.Testability)) { return this._Testability_28; }
    if ((token === import3.Meta)) { return this._Meta_29; }
    if ((token === import3.Title)) { return this._Title_30; }
    if ((token === import4.BrowserXhr)) { return this._BrowserXhr_31; }
    if ((token === import4.ResponseOptions)) { return this._ResponseOptions_32; }
    if ((token === import4.XSRFStrategy)) { return this._XSRFStrategy_33; }
    if ((token === import4.XHRBackend)) { return this._XHRBackend_34; }
    if ((token === import4.RequestOptions)) { return this._RequestOptions_35; }
    if ((token === import4.Http)) { return this._Http_36; }
    if ((token === import5.ɵi)) { return this._ɵi_37; }
    if ((token === import5.FormBuilder)) { return this._FormBuilder_38; }
    if ((token === import6.ErrorService)) { return this._ErrorService_39; }
    if ((token === import7.SwaggerService)) { return this._SwaggerService_40; }
    if ((token === import8.ApiKeyProvider)) { return this._ApiKeyProvider_41; }
    if ((token === import9.AuthService)) { return this._AuthService_42; }
    if ((token === import10.RequestBuilder)) { return this._RequestBuilder_43; }
    if ((token === import11.HttpService)) { return this._HttpService_44; }
    return notFoundResult;
  }
  destroyInternal():void {
    this._ɵf_4.ngOnDestroy();
    (this.__ɵDomSharedStylesHost_24 && this._ɵDomSharedStylesHost_24.ngOnDestroy());
  }
}
export const SwangularModuleNgFactory:import0.NgModuleFactory<import1.SwangularModule> = new import0.NgModuleFactory<any>(SwangularModuleInjector,import1.SwangularModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21sYXR0dWFkYS9Eb2N1bWVudHMvUHJvamVjdHMvc3dhbmd1bGFyLWNvbXBvbmVudHMvaW5kZXgubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbWxhdHR1YWRhL0RvY3VtZW50cy9Qcm9qZWN0cy9zd2FuZ3VsYXItY29tcG9uZW50cy9pbmRleC50cyJdLCJzb3VyY2VzQ29udGVudCI6WyIgIl0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
