/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../components/http-status-label/http-status-label.component';
const styles_HttpStatusLabelComponent:any[] = ['.label[_ngcontent-%COMP%] { padding-top: 0.4em; }'];
export const RenderType_HttpStatusLabelComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_HttpStatusLabelComponent,
  data: {}
}
);
export function View_HttpStatusLabelComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),3,'span',[[
        'class',
        'label'
      ]
    ],[
      [
        2,
        'label-success',
        (null as any)
      ]
      ,
      [
        2,
        'label-info',
        (null as any)
      ]
      ,
      [
        2,
        'label-warning',
        (null as any)
      ]
      ,
      [
        2,
        'label-danger',
        (null as any)
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ' '
    ]
    )),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'badge'
      ]
    ],(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.HttpStatusLabelComponent = v.component;
    const currVal_0:any = co.isSuccess();
    const currVal_1:any = co.isRedirect();
    const currVal_2:any = co.isClientError();
    const currVal_3:any = co.isServerError();
    ck(v,1,0,currVal_0,currVal_1,currVal_2,currVal_3);
    const currVal_4:any = co.status;
    ck(v,2,0,currVal_4);
    const currVal_5:any = co.statusCode;
    ck(v,4,0,currVal_5);
  });
}
function View_HttpStatusLabelComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'http-status-label',([] as any[]),(null as any),(null as any),(null as any),View_HttpStatusLabelComponent_0,RenderType_HttpStatusLabelComponent)),
    import0.ɵdid(24576,(null as any),0,import1.HttpStatusLabelComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HttpStatusLabelComponentNgFactory:import0.ComponentFactory<import1.HttpStatusLabelComponent> = import0.ɵccf('http-status-label',import1.HttpStatusLabelComponent,View_HttpStatusLabelComponent_Host_0,{
  statusCode: 'statusCode',
  status: 'status'
}
,{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21sYXR0dWFkYS9Eb2N1bWVudHMvUHJvamVjdHMvc3dhbmd1bGFyLWNvbXBvbmVudHMvY29tcG9uZW50cy9odHRwLXN0YXR1cy1sYWJlbC9odHRwLXN0YXR1cy1sYWJlbC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbWxhdHR1YWRhL0RvY3VtZW50cy9Qcm9qZWN0cy9zd2FuZ3VsYXItY29tcG9uZW50cy9jb21wb25lbnRzL2h0dHAtc3RhdHVzLWxhYmVsL2h0dHAtc3RhdHVzLWxhYmVsLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL21sYXR0dWFkYS9Eb2N1bWVudHMvUHJvamVjdHMvc3dhbmd1bGFyLWNvbXBvbmVudHMvY29tcG9uZW50cy9odHRwLXN0YXR1cy1sYWJlbC9odHRwLXN0YXR1cy1sYWJlbC5jb21wb25lbnQudHMuSHR0cFN0YXR1c0xhYmVsQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9tbGF0dHVhZGEvRG9jdW1lbnRzL1Byb2plY3RzL3N3YW5ndWxhci1jb21wb25lbnRzL2NvbXBvbmVudHMvaHR0cC1zdGF0dXMtbGFiZWwvaHR0cC1zdGF0dXMtbGFiZWwuY29tcG9uZW50LnRzLkh0dHBTdGF0dXNMYWJlbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxzcGFuIGNsYXNzPVwibGFiZWxcIlxuICAgICAgICAgW2NsYXNzLmxhYmVsLXN1Y2Nlc3NdPVwiaXNTdWNjZXNzKClcIlxuICAgICAgICAgW2NsYXNzLmxhYmVsLWluZm9dPVwiaXNSZWRpcmVjdCgpXCJcbiAgICAgICAgIFtjbGFzcy5sYWJlbC13YXJuaW5nXT1cImlzQ2xpZW50RXJyb3IoKVwiXG4gICAgICAgICBbY2xhc3MubGFiZWwtZGFuZ2VyXT1cImlzU2VydmVyRXJyb3IoKVwiPnt7c3RhdHVzfX0gPHNwYW4gY2xhc3M9XCJiYWRnZVwiPnt7c3RhdHVzQ29kZX19PC9zcGFuPjwvc3Bhbj5cbiAgIiwiPGh0dHAtc3RhdHVzLWxhYmVsPjwvaHR0cC1zdGF0dXMtbGFiZWw+Il0sIm1hcHBpbmdzIjoiQUFBQTs7Ozs7Ozs7Ozs7Ozs7Ozs7OztJQ0FBO01BQ0k7UUFBQTtRQUFBO01BQUE7SUFBQTtNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQUk0QztNQUFBO01BQUE7SUFBQTtJQUFBO01BQVc7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUFvQjtNQUFBO01BQUE7SUFBQTtJQUFBO0lBQTRCOzs7O0lBSGxHO0lBQ0E7SUFDQTtJQUNBO0lBSkwsU0FDSyxVQUNBLFVBQ0EsVUFDQSxTQUpMO0lBSTRDO0lBQUE7SUFBK0I7SUFBQTs7Ozs7SUNML0U7Z0JBQUE7Ozs7Ozs7OyJ9
