/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '@angular/common';
import * as import2 from '../../../components/auth-callback/auth-callback.component';
import * as import3 from '../../../services/auth.service';
import * as import4 from '../../../services/error.service';
const styles_AuthCallbackComponent:any[] = ([] as any[]);
export const RenderType_AuthCallbackComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_AuthCallbackComponent,
  data: {}
}
);
function View_AuthCallbackComponent_1(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),8,'div',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'h5',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['Last response'])),
    (l()(),import0.ɵted((null as any),['\n      '])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),2,'pre',([] as any[]),(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    import0.ɵpid(0,import1.JsonPipe,([] as any[])),
    (l()(),import0.ɵted((null as any),['\n    ']))
  ]
  ,(null as any),(ck,v) => {
    var co:any = v.component;
    const currVal_0:any = import0.ɵunv(v,6,0,import0.ɵnov(v,7).transform(co.response));
    ck(v,6,0,currVal_0);
  });
}
export function View_AuthCallbackComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
    (l()(),import0.ɵand(8388608,(null as any),(null as any),1,(null as any),View_AuthCallbackComponent_1)),
    import0.ɵdid(8192,(null as any),0,import1.NgIf,[
      import0.ViewContainerRef,
      import0.TemplateRef
    ]
      ,{ngIf: [
        0,
        'ngIf'
      ]
    },(null as any)),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(ck,v) => {
    var co:import2.AuthCallbackComponent = v.component;
    const currVal_0:any = co.showResponse;
    ck(v,2,0,currVal_0);
  },(null as any));
}
function View_AuthCallbackComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'auth-callback',([] as any[]),(null as any),(null as any),(null as any),View_AuthCallbackComponent_0,RenderType_AuthCallbackComponent)),
    import0.ɵdid(122880,(null as any),0,import2.AuthCallbackComponent,[
      import0.NgZone,
      import3.AuthService,
      import4.ErrorService
    ]
    ,(null as any),(null as any))
  ]
  ,(ck,v) => {
    ck(v,1,0);
  },(null as any));
}
export const AuthCallbackComponentNgFactory:import0.ComponentFactory<import2.AuthCallbackComponent> = import0.ɵccf('auth-callback',import2.AuthCallbackComponent,View_AuthCallbackComponent_Host_0,{showResponse: 'showResponse'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21sYXR0dWFkYS9Eb2N1bWVudHMvUHJvamVjdHMvc3dhbmd1bGFyLWNvbXBvbmVudHMvY29tcG9uZW50cy9hdXRoLWNhbGxiYWNrL2F1dGgtY2FsbGJhY2suY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL21sYXR0dWFkYS9Eb2N1bWVudHMvUHJvamVjdHMvc3dhbmd1bGFyLWNvbXBvbmVudHMvY29tcG9uZW50cy9hdXRoLWNhbGxiYWNrL2F1dGgtY2FsbGJhY2suY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvbWxhdHR1YWRhL0RvY3VtZW50cy9Qcm9qZWN0cy9zd2FuZ3VsYXItY29tcG9uZW50cy9jb21wb25lbnRzL2F1dGgtY2FsbGJhY2svYXV0aC1jYWxsYmFjay5jb21wb25lbnQudHMuQXV0aENhbGxiYWNrQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9tbGF0dHVhZGEvRG9jdW1lbnRzL1Byb2plY3RzL3N3YW5ndWxhci1jb21wb25lbnRzL2NvbXBvbmVudHMvYXV0aC1jYWxsYmFjay9hdXRoLWNhbGxiYWNrLmNvbXBvbmVudC50cy5BdXRoQ2FsbGJhY2tDb21wb25lbnRfSG9zdC5odG1sIl0sInNvdXJjZXNDb250ZW50IjpbIiAiLCJcbiAgICA8ZGl2ICpuZ0lmPVwic2hvd1Jlc3BvbnNlXCI+XG4gICAgICA8aDU+TGFzdCByZXNwb25zZTwvaDU+XG4gICAgICA8cHJlPnt7cmVzcG9uc2UgfCBqc29ufX08L3ByZT5cbiAgICA8L2Rpdj5cbiAgIiwiPGF1dGgtY2FsbGJhY2s+PC9hdXRoLWNhbGxiYWNrPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNDSTtJQUEwQjtJQUN4QjtJQUFJO0lBQWtCO0lBQ3RCO0lBQUs7TUFBQTtNQUFBO0lBQUE7SUFBQTtnQkFBQTtJQUF5Qjs7OztJQUF6QjtJQUFBOzs7OztJQUhYO0lBQ0k7Z0JBQUE7OztJQUFBO09BQUE7UUFBQTtRQUFBO01BQUE7SUFBQTtJQUdNOzs7O0lBSEQ7SUFBTCxTQUFLLFNBQUw7Ozs7O0lDREo7Z0JBQUE7Ozs7SUFBQTtLQUFBOzs7SUFBQTs7OyJ9
