/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from '../../../components/http-method-label/http-method-label.component';
const styles_HttpMethodLabelComponent:any[] = ['.label[_ngcontent-%COMP%] { padding-top: 0.4em; }'];
export const RenderType_HttpMethodLabelComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 0,
  styles: styles_HttpMethodLabelComponent,
  data: {}
}
);
export function View_HttpMethodLabelComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),1,'span',[[
        'class',
        'label text-uppercase'
      ]
    ],[
      [
        2,
        'label-info',
        (null as any)
      ]
      ,
      [
        2,
        'label-success',
        (null as any)
      ]
      ,
      [
        2,
        'label-warning',
        (null as any)
      ]
      ,
      [
        2,
        'label-danger',
        (null as any)
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),[
      '',
      ''
    ]
    )),
    (l()(),import0.ɵted((null as any),['\n  ']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.HttpMethodLabelComponent = v.component;
    const currVal_0:any = co.isGet();
    const currVal_1:any = co.isPost();
    const currVal_2:any = co.isPutOrPatch();
    const currVal_3:any = co.isDelete();
    ck(v,1,0,currVal_0,currVal_1,currVal_2,currVal_3);
    const currVal_4:any = co.getMethodName();
    ck(v,2,0,currVal_4);
  });
}
function View_HttpMethodLabelComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'http-method-label',([] as any[]),(null as any),(null as any),(null as any),View_HttpMethodLabelComponent_0,RenderType_HttpMethodLabelComponent)),
    import0.ɵdid(24576,(null as any),0,import1.HttpMethodLabelComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const HttpMethodLabelComponentNgFactory:import0.ComponentFactory<import1.HttpMethodLabelComponent> = import0.ɵccf('http-method-label',import1.HttpMethodLabelComponent,View_HttpMethodLabelComponent_Host_0,{method: 'method'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL21sYXR0dWFkYS9Eb2N1bWVudHMvUHJvamVjdHMvc3dhbmd1bGFyLWNvbXBvbmVudHMvY29tcG9uZW50cy9odHRwLW1ldGhvZC1sYWJlbC9odHRwLW1ldGhvZC1sYWJlbC5jb21wb25lbnQubmdmYWN0b3J5LnRzIiwidmVyc2lvbiI6Mywic291cmNlUm9vdCI6IiIsInNvdXJjZXMiOlsibmc6Ly8vVXNlcnMvbWxhdHR1YWRhL0RvY3VtZW50cy9Qcm9qZWN0cy9zd2FuZ3VsYXItY29tcG9uZW50cy9jb21wb25lbnRzL2h0dHAtbWV0aG9kLWxhYmVsL2h0dHAtbWV0aG9kLWxhYmVsLmNvbXBvbmVudC50cyIsIm5nOi8vL1VzZXJzL21sYXR0dWFkYS9Eb2N1bWVudHMvUHJvamVjdHMvc3dhbmd1bGFyLWNvbXBvbmVudHMvY29tcG9uZW50cy9odHRwLW1ldGhvZC1sYWJlbC9odHRwLW1ldGhvZC1sYWJlbC5jb21wb25lbnQudHMuSHR0cE1ldGhvZExhYmVsQ29tcG9uZW50Lmh0bWwiLCJuZzovLy9Vc2Vycy9tbGF0dHVhZGEvRG9jdW1lbnRzL1Byb2plY3RzL3N3YW5ndWxhci1jb21wb25lbnRzL2NvbXBvbmVudHMvaHR0cC1tZXRob2QtbGFiZWwvaHR0cC1tZXRob2QtbGFiZWwuY29tcG9uZW50LnRzLkh0dHBNZXRob2RMYWJlbENvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuICAgIDxzcGFuIGNsYXNzPVwibGFiZWwgdGV4dC11cHBlcmNhc2VcIlxuICAgICAgICAgW2NsYXNzLmxhYmVsLWluZm9dPVwiaXNHZXQoKVwiXG4gICAgICAgICBbY2xhc3MubGFiZWwtc3VjY2Vzc109XCJpc1Bvc3QoKVwiXG4gICAgICAgICBbY2xhc3MubGFiZWwtd2FybmluZ109XCJpc1B1dE9yUGF0Y2goKVwiXG4gICAgICAgICBbY2xhc3MubGFiZWwtZGFuZ2VyXT1cImlzRGVsZXRlKClcIj57e2dldE1ldGhvZE5hbWUoKX19PC9zcGFuPlxuICAiLCI8aHR0cC1tZXRob2QtbGFiZWw+PC9odHRwLW1ldGhvZC1sYWJlbD4iXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7O0lDQUE7TUFDSTtRQUFBO1FBQUE7TUFBQTtJQUFBO01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7TUFBQTtRQUFBO1FBQUE7UUFBQTtNQUFBOztNQUFBO1FBQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO1FBQUE7TUFBQTs7SUFBQTtLQUFBO0lBSXVDO01BQUE7TUFBQTtJQUFBO0lBQUE7SUFBMEI7Ozs7SUFINUQ7SUFDQTtJQUNBO0lBQ0E7SUFKTCxTQUNLLFVBQ0EsVUFDQSxVQUNBLFNBSkw7SUFJdUM7SUFBQTs7Ozs7SUNMM0M7Z0JBQUE7Ozs7In0=
